apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-rollout
spec:
  replicas: 1
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: staging-backend-virtualservice
          destinationRule:
            name: staging-backend-destinationrule
  template:
    spec:
      serviceAccountName: staging-backend
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backend
          image: ghcr.io/atkaridarshan04/cloudnative-devops-blueprint/bookstore-backend # Tag managed by Kustomize images
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: staging-backend-config
                  key: PORT
            - name: mongoDBURL
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials-external
                  key: MONGODB_URL
          livenessProbe:
            httpGet:
              path: /books
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /books
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-rollout
spec:
  replicas: 1
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: staging-frontend-virtualservice
          destinationRule:
            name: staging-frontend-destinationrule
  template:
    spec:
      hostUsers: false
      serviceAccountName: staging-frontend
      containers:
        - name: frontend
          image: ghcr.io/atkaridarshan04/cloudnative-devops-blueprint/bookstore-frontend # Tag managed by Kustomize images
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: backend-destinationrule
spec:
  host: staging-backend-service
  subsets:
    - name: stable
      labels:
        app: backend
    - name: canary
      labels:
        app: backend

---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: frontend-destinationrule
spec:
  host: staging-frontend-service
  subsets:
    - name: stable
      labels:
        app: frontend
    - name: canary
      labels:
        app: frontend

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: backend-virtualservice
spec:
  hosts:
    - staging-backend-service
  http:
    - name: primary
      route:
        - destination:
            host: staging-backend-service
            subset: stable
          weight: 100
        - destination:
            host: staging-backend-service
            subset: canary
          weight: 0

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: frontend-virtualservice
spec:
  hosts:
    - staging-frontend-service
  http:
    - name: primary
      route:
        - destination:
            host: staging-frontend-service
            subset: stable
          weight: 100
        - destination:
            host: staging-frontend-service
            subset: canary
          weight: 0
