---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: mern-devops
spec:
  secretName: wildcard-tls
  dnsNames:
    - '*.cndb.atkaridarshan.online'
  issuerRef:
    name: letsencrypt-prod # Use `letsencrypt-prod` for production
    kind: ClusterIssuer
    group: cert-manager.io
