namespace: mern-devops

gateway:
  name: envoy-gateway
  hostname: app.cndb.atkaridarshan.online

frontend:
  replicas: 1
  image:
    repository: ghcr.io/atkaridarshan04/cloudnative-devops-blueprint/bookstore-frontend
    tag: 3.0.0
  containerPort: 80

  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15

  service:
    type: ClusterIP
    port: 80

  config:
    backendUrl: ""


backend:
  replicas: 1
  image:
    repository: ghcr.io/atkaridarshan04/cloudnative-devops-blueprint/bookstore-backend
    tag: 3.0.0
  containerPort: 8000

  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15

  service:
    type: ClusterIP
    port: 8000


mongodb:
  replicas: 1
  image: mongo:4.4
  serviceName: mongodb-service
  serviceType: ClusterIP

  username: admin
  password: password123
  dbName: db

  authSource: admin
