apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: book-store
  namespace: book-store
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
    - stageSelector:
        name: staging
      autoPromotionEnabled: true
    - stageSelector:
        name: prod
      autoPromotionEnabled: false
