# staging only requests Freight that's already been verified (promoted successfully) in dev.
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: book-store
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: book-store
      sources:
        stages:
          - dev

  promotionTemplate:
    spec:
      vars:
        - name: overlayPath
          value: kustomize/overlays/staging
        - name: appName
          value: book-store-staging
        - name: branch
          value: kargo-promotion # switch to main once this merges
      steps:
        - task:
            name: promote-overlay
          as: promote
