apiVersion: v1
kind: ConfigMap
metadata: 
  name: backend-config
  namespace: mern-devops
data:
  PORT: "8000"
  mongoDBURL: "mongodb://admin:password123@mongodb-deployment-0.mongodb-service-headless.mern-devops.svc.cluster.local:27017/db?authSource=admin"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-devops
  labels:
    app: backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      name: backend
      labels:
        app: backend
        version: v1
    spec:
      containers:
        - name: backend
          image: atkaridarshan04/bookstore-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: mongoDBURL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mongoDBURL  
          livenessProbe:
            httpGet:
              path: /books
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /books
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-devops
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP