apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: mern-devops
data:
  VITE_API_BACKEND_URL: ""  # after configuring ingress or istio

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-devops
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: atkaridarshan04/bookstore-frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: frontend-config
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 30
            periodSeconds: 15  
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-devops
spec:
  selector:
    app: frontend
    version: v1
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP