---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mern-devops
type: Opaque
data:
  username: YWRtaW4=            # base64 encoded for 'admin'
  password: cGFzc3dvcmQxMjM=    # base64 encoded for 'password123'

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-headless
  namespace: mern-devops
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deployment
  namespace: mern-devops
  labels:
    app: mongodb
spec:
  serviceName: "mongodb-service-headless"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  updateStrategy:
    type: RollingUpdate   
    rollingUpdate:
      partition: 0
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: "db"