apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-external-secret
  namespace: mern-devops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mongodb-credentials-external # The name of the K8s Secret created
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Reconstructing the URL here is the "Standard" way
        MONGODB_URL: "mongodb://{{ .username }}:{{ .password }}@mongodb-deployment-0.mongodb-service-headless.mern-devops.svc.cluster.local:27017/db?authSource=admin"
        # Standardized naming for the app environment variables
        MONGODB_USER: "{{ .username }}"
        MONGODB_PASSWORD: "{{ .password }}"
  data:
  - secretKey: username # This matches the key INSIDE Vault
    remoteRef:
      key: dev/mern-backend/mongodb
      property: username
  - secretKey: password # This matches the key INSIDE Vault
    remoteRef:
      key: dev/mern-backend/mongodb
      property: password