apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          image: atkaridarshan04/bookstore-backend  # Tag managed by Kustomize images

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: frontend
          image: atkaridarshan04/bookstore-frontend  # Tag managed by Kustomize images
