apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mern-devops
# namePrefix: prod-

resources:
  - ../../base

patches:
  - path: backend-patch.yml
  - path: frontend-patch.yml
