apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.backend.containerPort }}"
  mongoDBURL: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Release.Name }}-{{ .Values.mongodb.serviceName }}:27017/{{ .Values.mongodb.dbName }}?authSource={{ .Values.mongodb.authSource }}"

---
apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-backend-service-stable
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP

---
apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-backend-service-canary
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-backend-rollout
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  strategy:
    canary:
      canaryService: {{ .Release.Name }}-backend-service-canary
      stableService: {{ .Release.Name }}-backend-service-stable
      trafficRouting:
        nginx:
          stableIngress: {{ .Release.Name }}-nginx-stable
      steps:
      - setWeight: 20
      - pause: {} # Manual intervention step
      - setWeight: 60
      - pause: { duration: 10s } 
      - setWeight: 100
      - pause: { duration: 10s }
  revisionHistoryLimit: 2 # Keep the last 2 revisions
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          envFrom:
            - configMapRef: 
                name: {{ .Release.Name }}-backend-config
          livenessProbe:
            httpGet: 
              path: /books 
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /books
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}

---