apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book-store-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: book-store

  source:
    repoURL: https://github.com/atkaridarshan04/CloudNative-DevOps-Blueprint.git
    targetRevision: main
    path: kustomize/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
