apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book-store-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: book-store

  source:
    repoURL: https://github.com/atkaridarshan04/CloudNative-DevOps-Blueprint.git
    targetRevision: kargo-promotion # working branch — switch back to main once this merges
    path: kustomize/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
