apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # 
    # Enable notifications for specific triggers and specify recipient email addresses
    notifications.argoproj.io/subscribe.on-health-degraded.email: "atkaridarshan04@gmail.com"
    notifications.argoproj.io/subscribe.on-deployed.email: "atkaridarshan04@gmail.com, darshan.atkari23@vit.edu"
spec:
  project: book-store
  source:
    repoURL: https://github.com/atkaridarshan04/CloudNative-DevOps-Blueprint.git
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: mern-devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
