apiVersion: v1
kind: ConfigMap
metadata: 
  name: backend-config
  namespace: mern-devops
data:
  PORT: "8000"
  # mongoDBURL: "mongodb://admin:password123@mongodb-service:27017/db?authSource=admin"      # using service name

  mongoDBURL: "mongodb://admin:password123@mongodb-deployment-0.mongodb-service-headless.mern-devops.svc.cluster.local:27017/db?authSource=admin"       # using headless service name
  
# The format for the DNS name of a service in Kubernetes is: <pod-name>.<service-name>.<namespace>.svc.cluster.local