apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deployment
  namespace: mern-devops
  labels:
    app: mongodb
spec:
  # minAvailable: 2 
  serviceName: "mongodb-service-headless"   # This should matches the service name
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          imagePullPolicy: IfNotPresent   
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: "db"
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "0.25"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "0.25"
          volumeMounts:
            - name: mongodb-vol
              mountPath: /data/db
      volumes:
        - name: mongodb-vol
          persistentVolumeClaim:
            claimName: mongo-pvc
  # volumeClaimTemplates:   # When not using persistentVolumeClaim seperately
  #   - metadata:
  #       name: mongodb-vol
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       storageClassName: manual
  #       resources:
  #         requests:
  #           storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-headless
  namespace: mern-devops
spec:
  selector:
    app: mongodb
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP