# The Gateway creates the entry point for external traffic into the mesh.
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: mern-devops
spec:
  selector:
    istio: ingress # use Istio's built-in ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"