apiVersion: v1
kind: ConfigMap
metadata: 
  name: backend-config
data:
  PORT: "8000"
  mongoDBURL: "mongodb://admin:password123@mongodb-deployment-0.mongodb-service-headless.mern-devops.svc.cluster.local:27017/db?authSource=admin"