apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_API_BACKEND_URL: http://192.168.88.133:31100 # using nodeport service
  # VITE_API_BACKEND_URL: "" # after configuring ingress or domain for ingress-ip

