apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mern-devops

resources:
  - mongodb.yml
  - httproute.yml
  - backend.yml
  - frontend.yml
  # - volume.yml

secretGenerator:
  - name: mongo-secret
    literals:
      - username=admin
      - password=password123
