apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mern-devops
# namePrefix: dev-

resources:
  - ../../base

patches:
  - path: patches/backend-patch.yml
  - path: patches/frontend-patch.yml
