apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The ':latest' tag is mutable and can lead to unexpected errors if the
      image changes. A best practice is to use an immutable tag that maps to
      a specific version of an application Pod. This policy validates that the image
      specifies a tag and that it is not called `latest`.
spec:
  # Enforcement mode - blocks pods with latest tags from being created
  # Use 'Audit' mode initially to identify violations without blocking deployments
  validationFailureAction: Enforce
  
  # Background scanning - evaluates existing pods when policy is updated
  # Helps identify legacy workloads that need tag updates
  background: true
  
  rules:
  # Rule 1: Ensure all container images have explicit tags
  # Prevents implicit ':latest' tag usage when no tag is specified
  - name: require-image-tag
    match:
      any:
      - resources:
          kinds:
          - Pod  # Applies to pods created by Deployments, StatefulSets, DaemonSets
    validate:
      message: "An image tag is required."
      foreach:
        # Main application containers - primary workload containers
        - list: "request.object.spec.containers"
          pattern:
            # Pattern matching - image must contain colon followed by tag
            image: "*:*"  # Must contain colon followed by tag (e.g., nginx:1.21)
        # Init containers - setup/migration containers that run before main containers
        - list: "request.object.spec.initContainers"
          pattern:
            image: "*:*"  # Init containers also need explicit tags for reproducibility (# Critical for database migrations, setup scripts, etc.)
        # Ephemeral containers - debug containers injected at runtime
        - list: "request.object.spec.ephemeralContainers"
          pattern:
            image: "*:*"  # Debug containers should use specific tool versions
  
  # Rule 2: Explicitly prohibit 'latest' tag usage
  # Prevents mutable tags that can cause deployment inconsistencies
  - name: validate-image-tag
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Using a mutable image tag e.g. 'latest' is not allowed."
      foreach:
        - list: "request.object.spec.containers"          # Application containers
          pattern:
            image: "!*:latest"
        - list: "request.object.spec.initContainers"      # Init containers
          pattern:
            image: "!*:latest" 
        - list: "request.object.spec.ephemeralContainers" # Ephemeral containers
          pattern:
            image: "!*:latest"